[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = false
optimizer_runs = 200

# Forking Ethereum mainnet
eth_rpc_url = "https://mainnet.infura.io/v3/d0f7032fae834d4f90791e42dd6f9846"
private_keys = ["DO_NOT_LEAK"]
fork_block_number = 20922361
rpc_storage_caching = { chains = "all", endpoints = "all" }


[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
